# Generated by Django 5.0.14 on 2026-05-29 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteertask",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
