# Generated by Django 5.0.14 on 2026-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_volunteertask_volunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="cnn_confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
