# Generated by Django 5.0.14 on 2026-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_donation_cnn_confidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ngo_assigned", "NGO Assigned"),
                    ("en_route", "En Route"),
                    ("picked_up", "Picked Up"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
